#ifndef __UNIFIED_CHARACTER_DISPLAY_CONFIG_H__
#define __UNIFIED_CHARACTER_DISPLAY_CONFIG_H__


//#undef LCD_HAL_USE_GROVE
//#undef LCD_HAL_USE_LIQUID_CRYSTAL
//#undef LCD_HAL_USE_ACM1602NI

#endif /* __UNIFIED_CHARACTER_DISPLAY_CONFIG_H__ */