#ifndef __UNIFIED_CHARACTER_DISPLAY_CONFIG_H__
#define __UNIFIED_CHARACTER_DISPLAY_CONFIG_H__

#define LCD_HAL_USE_GROVE
#define LCD_HAL_USE_LIQUID_CRYSTAL
#define LCD_HAL_USE_ACM1602NI

#endif /* __UNIFIED_CHARACTER_DISPLAY_CONFIG_H__ */